package com.fym.dao;

import java.util.List;

import com.fym.entity.RechargeLog;

public interface RechargeLogMapper {
	List<RechargeLog> selectAll();
   
	List<RechargeLog> selectByUserId(int id);
	
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_log
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int insert(RechargeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_log
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int insertSelective(RechargeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_log
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    RechargeLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_log
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int updateByPrimaryKeySelective(RechargeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_log
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int updateByPrimaryKey(RechargeLog record);
}