package com.fym.dao;

import java.util.List;

import com.fym.entity.ShopAd;

public interface ShopAdMapper {
	
	List<ShopAd> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int insert(ShopAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int insertSelective(ShopAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    ShopAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int updateByPrimaryKeySelective(ShopAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ShopAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int updateByPrimaryKey(ShopAd record);
}