package com.fym.dao;

import com.fym.entity.ShopOrderGoods;

public interface ShopOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int insert(ShopOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int insertSelective(ShopOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    ShopOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int updateByPrimaryKeySelective(ShopOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int updateByPrimaryKey(ShopOrderGoods record);
}