package com.fym.dao;

import java.util.List;

import com.fym.entity.UserCartLog;

public interface UserCartLogMapper {
	List<UserCartLog> selectByUserId(int id);
    
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cart_log
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int insert(UserCartLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cart_log
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int insertSelective(UserCartLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cart_log
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    UserCartLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cart_log
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int updateByPrimaryKeySelective(UserCartLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cart_log
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    int updateByPrimaryKey(UserCartLog record);
}