package com.fym.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Goods {
    
    private Integer id;

    private String goodsName;

    private String goodsImg;

    private String goodsSn;

    private BigDecimal marketPrice;

    private BigDecimal sellPrice;

    private Integer goodsNumber;

    private Integer isOnSale;

    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date addTime;

    private Integer clickCount;

    private Integer isNew;
    
    private Integer catalogId;

    private Integer isHot;

    private String description;
    
    

    @Override
	public String toString() {
		return "Goods [id=" + id + ", goodsName=" + goodsName + ", goodsImg=" + goodsImg + ", goodsSn=" + goodsSn
				+ ", marketPrice=" + marketPrice + ", sellPrice=" + sellPrice + ", goodsNumber=" + goodsNumber
				+ ", isOnSale=" + isOnSale + ", addTime=" + addTime + ", clickCount=" + clickCount + ", isNew=" + isNew
				+ ", catalogId=" + catalogId + ", isHot=" + isHot + ", description=" + description + "]";
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_name
     *
     * @return the value of goods.goods_name
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_name
     *
     * @param goodsName the value for goods.goods_name
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_img
     *
     * @return the value of goods.goods_img
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_img
     *
     * @param goodsImg the value for goods.goods_img
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg == null ? null : goodsImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_sn
     *
     * @return the value of goods.goods_sn
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_sn
     *
     * @param goodsSn the value for goods.goods_sn
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.market_price
     *
     * @return the value of goods.market_price
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.market_price
     *
     * @param marketPrice the value for goods.market_price
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sell_price
     *
     * @return the value of goods.sell_price
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public BigDecimal getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sell_price
     *
     * @param sellPrice the value for goods.sell_price
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_number
     *
     * @return the value of goods.goods_number
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_number
     *
     * @param goodsNumber the value for goods.goods_number
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setGoodsNumber(Integer goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.is_on_sale
     *
     * @return the value of goods.is_on_sale
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getIsOnSale() {
        return isOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.is_on_sale
     *
     * @param isOnSale the value for goods.is_on_sale
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setIsOnSale(Integer isOnSale) {
        this.isOnSale = isOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.add_time
     *
     * @return the value of goods.add_time
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.add_time
     *
     * @param addTime the value for goods.add_time
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.click_count
     *
     * @return the value of goods.click_count
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getClickCount() {
        return clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.click_count
     *
     * @param clickCount the value for goods.click_count
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setClickCount(Integer clickCount) {
        this.clickCount = clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.is_new
     *
     * @return the value of goods.is_new
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.is_new
     *
     * @param isNew the value for goods.is_new
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setIsNew(Integer isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.catalog_id
     *
     * @return the value of goods.catalog_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.catalog_id
     *
     * @param catalogId the value for goods.catalog_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setCatalogId(Integer catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.is_hot
     *
     * @return the value of goods.is_hot
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.is_hot
     *
     * @param isHot the value for goods.is_hot
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setIsHot(Integer isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.description
     *
     * @return the value of goods.description
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.description
     *
     * @param description the value for goods.description
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}