package com.fym.entity;

import java.util.Date;

public class News {
   
    private Integer id;

   
    private String newsTitle;

    private String newsImg;

    private String subTitle;

    
    private Date addTime;

    private Integer countClick;

    private Integer commentCount;

    private Integer isShow;

    private Integer catalogId;

    private String description;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_title
     *
     * @return the value of news.news_title
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_title
     *
     * @param newsTitle the value for news.news_title
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle == null ? null : newsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_img
     *
     * @return the value of news.news_img
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getNewsImg() {
        return newsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_img
     *
     * @param newsImg the value for news.news_img
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setNewsImg(String newsImg) {
        this.newsImg = newsImg == null ? null : newsImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.sub_title
     *
     * @return the value of news.sub_title
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.sub_title
     *
     * @param subTitle the value for news.sub_title
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.add_time
     *
     * @return the value of news.add_time
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.add_time
     *
     * @param addTime the value for news.add_time
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.count_click
     *
     * @return the value of news.count_click
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getCountClick() {
        return countClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.count_click
     *
     * @param countClick the value for news.count_click
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setCountClick(Integer countClick) {
        this.countClick = countClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.comment_count
     *
     * @return the value of news.comment_count
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.comment_count
     *
     * @param commentCount the value for news.comment_count
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.is_show
     *
     * @return the value of news.is_show
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.is_show
     *
     * @param isShow the value for news.is_show
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.catalog_id
     *
     * @return the value of news.catalog_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.catalog_id
     *
     * @param catalogId the value for news.catalog_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setCatalogId(Integer catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.description
     *
     * @return the value of news.description
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.description
     *
     * @param description the value for news.description
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}