package com.fym.entity;

public class NewsCatalog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_catalog.id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_catalog.name
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_catalog.catalog_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    private Integer catalogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_catalog.remark
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_catalog.id
     *
     * @return the value of news_catalog.id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_catalog.id
     *
     * @param id the value for news_catalog.id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_catalog.name
     *
     * @return the value of news_catalog.name
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_catalog.name
     *
     * @param name the value for news_catalog.name
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_catalog.catalog_id
     *
     * @return the value of news_catalog.catalog_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_catalog.catalog_id
     *
     * @param catalogId the value for news_catalog.catalog_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setCatalogId(Integer catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_catalog.remark
     *
     * @return the value of news_catalog.remark
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_catalog.remark
     *
     * @param remark the value for news_catalog.remark
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}