package com.fym.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RechargeLog {
    
    private Integer id;

    private Integer userId;

    private String rechargeSn;

    private Date addTime;

    private BigDecimal money;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_log.id
     *
     * @param id the value for recharge_log.id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_log.user_id
     *
     * @return the value of recharge_log.user_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_log.user_id
     *
     * @param userId the value for recharge_log.user_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_log.recharge_sn
     *
     * @return the value of recharge_log.recharge_sn
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getRechargeSn() {
        return rechargeSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_log.recharge_sn
     *
     * @param rechargeSn the value for recharge_log.recharge_sn
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setRechargeSn(String rechargeSn) {
        this.rechargeSn = rechargeSn == null ? null : rechargeSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_log.add_time
     *
     * @return the value of recharge_log.add_time
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_log.add_time
     *
     * @param addTime the value for recharge_log.add_time
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_log.money
     *
     * @return the value of recharge_log.money
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_log.money
     *
     * @param money the value for recharge_log.money
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }
}