package com.fym.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class ShopOrderGoods {
   
    private Integer id;

    private Integer goodsId;

    private Integer userId;

    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date addTime;

    private String goodsName;

    private String goodsImg;

    private BigDecimal price;

    private Integer goNum;

    private BigDecimal totalPrice;

    private Integer orderId;

    private String goodsSn;

    private Integer catalogId;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_goods.id
     *
     * @param id the value for shop_order_goods.id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_goods.goods_id
     *
     * @return the value of shop_order_goods.goods_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_goods.goods_id
     *
     * @param goodsId the value for shop_order_goods.goods_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_goods.user_id
     *
     * @return the value of shop_order_goods.user_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_goods.user_id
     *
     * @param userId the value for shop_order_goods.user_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_goods.add_time
     *
     * @return the value of shop_order_goods.add_time
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_goods.add_time
     *
     * @param addTime the value for shop_order_goods.add_time
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_goods.goods_name
     *
     * @return the value of shop_order_goods.goods_name
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_goods.goods_name
     *
     * @param goodsName the value for shop_order_goods.goods_name
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_goods.goods_img
     *
     * @return the value of shop_order_goods.goods_img
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_goods.goods_img
     *
     * @param goodsImg the value for shop_order_goods.goods_img
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg == null ? null : goodsImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_goods.price
     *
     * @return the value of shop_order_goods.price
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_goods.price
     *
     * @param price the value for shop_order_goods.price
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_goods.go_num
     *
     * @return the value of shop_order_goods.go_num
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getGoNum() {
        return goNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_goods.go_num
     *
     * @param goNum the value for shop_order_goods.go_num
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setGoNum(Integer goNum) {
        this.goNum = goNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_goods.total_price
     *
     * @return the value of shop_order_goods.total_price
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_goods.total_price
     *
     * @param totalPrice the value for shop_order_goods.total_price
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_goods.order_id
     *
     * @return the value of shop_order_goods.order_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_goods.order_id
     *
     * @param orderId the value for shop_order_goods.order_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_goods.goods_sn
     *
     * @return the value of shop_order_goods.goods_sn
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_goods.goods_sn
     *
     * @param goodsSn the value for shop_order_goods.goods_sn
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_goods.catalog_id
     *
     * @return the value of shop_order_goods.catalog_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_goods.catalog_id
     *
     * @param catalogId the value for shop_order_goods.catalog_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setCatalogId(Integer catalogId) {
        this.catalogId = catalogId;
    }
}