package com.fym.entity;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;

public class ShopOrder {
    
    private Integer id;

    private String orderSn;
    
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date addTime;

    private String userName;

    private String province;

    private String city;

    private String area;

    private String address;

    private String phone;

    private String email;

    private String code;

    private Integer shopState;

    private Integer userId;

    private BigDecimal totalMoney;

    private String remark;
    
    private List<ShopOrderGoods> shopOG;
    
    
   
	@Override
	public String toString() {
		return "ShopOrder [id=" + id + ", orderSn=" + orderSn + ", addTime=" + addTime + ", userName=" + userName
				+ ", province=" + province + ", city=" + city + ", area=" + area + ", address=" + address + ", phone="
				+ phone + ", email=" + email + ", code=" + code + ", shopState=" + shopState + ", userId=" + userId
				+ ", totalMoney=" + totalMoney + ", remark=" + remark + ", shopOG=" + shopOG + "]";
	}

	public List<ShopOrderGoods> getShopOG() {
		return shopOG;
	}

	public void setShopOG(List<ShopOrderGoods> shopOG) {
		this.shopOG = shopOG;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.id
     *
     * @return the value of shop_order.id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.id
     *
     * @param id the value for shop_order.id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.order_sn
     *
     * @return the value of shop_order.order_sn
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.order_sn
     *
     * @param orderSn the value for shop_order.order_sn
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.add_time
     *
     * @return the value of shop_order.add_time
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.add_time
     *
     * @param addTime the value for shop_order.add_time
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.user_name
     *
     * @return the value of shop_order.user_name
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.user_name
     *
     * @param userName the value for shop_order.user_name
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.province
     *
     * @return the value of shop_order.province
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.province
     *
     * @param province the value for shop_order.province
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.city
     *
     * @return the value of shop_order.city
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.city
     *
     * @param city the value for shop_order.city
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.area
     *
     * @return the value of shop_order.area
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.area
     *
     * @param area the value for shop_order.area
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.address
     *
     * @return the value of shop_order.address
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.address
     *
     * @param address the value for shop_order.address
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.phone
     *
     * @return the value of shop_order.phone
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.phone
     *
     * @param phone the value for shop_order.phone
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.email
     *
     * @return the value of shop_order.email
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.email
     *
     * @param email the value for shop_order.email
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.code
     *
     * @return the value of shop_order.code
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.code
     *
     * @param code the value for shop_order.code
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.shop_state
     *
     * @return the value of shop_order.shop_state
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getShopState() {
        return shopState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.shop_state
     *
     * @param shopState the value for shop_order.shop_state
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setShopState(Integer shopState) {
        this.shopState = shopState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.user_id
     *
     * @return the value of shop_order.user_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.user_id
     *
     * @param userId the value for shop_order.user_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.total_money
     *
     * @return the value of shop_order.total_money
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public BigDecimal getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.total_money
     *
     * @param totalMoney the value for shop_order.total_money
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setTotalMoney(BigDecimal totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.remark
     *
     * @return the value of shop_order.remark
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.remark
     *
     * @param remark the value for shop_order.remark
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}