package com.fym.entity;

import java.util.Date;

public class UserCartLog {
   
    private Integer id;

    private Integer userId;

    private Integer goodsId;

    private Date addTime;

    private Integer goNum;

    private Goods goods;
    
    
    
    public Goods getGoods() {
		return goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cart_log.id
     *
     * @param id the value for user_cart_log.id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cart_log.user_id
     *
     * @return the value of user_cart_log.user_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cart_log.user_id
     *
     * @param userId the value for user_cart_log.user_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cart_log.goods_id
     *
     * @return the value of user_cart_log.goods_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cart_log.goods_id
     *
     * @param goodsId the value for user_cart_log.goods_id
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cart_log.add_time
     *
     * @return the value of user_cart_log.add_time
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cart_log.add_time
     *
     * @param addTime the value for user_cart_log.add_time
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cart_log.go_num
     *
     * @return the value of user_cart_log.go_num
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public Integer getGoNum() {
        return goNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cart_log.go_num
     *
     * @param goNum the value for user_cart_log.go_num
     *
     * @mbg.generated Wed Sep 26 09:06:19 CST 2018
     */
    public void setGoNum(Integer goNum) {
        this.goNum = goNum;
    }
}